from .weather_station_info import WeatherStationInfo

class Source:
    location_name: str
    url: str
    url_is_video_stream: bool
    weather_data_provider: WeatherStationInfo | None
    def __init__(
        self,
        location_name: str,
        url: str,
        is_video_stream: bool = ...,
        weather_data_on_images: bool = ...,
        weather_data_provider: WeatherStationInfo | None = ...,
    ) -> None: ...
    @property
    def has_weather_data(self) -> bool: ...
    @property
    def is_valid_stream(self) -> bool: ...
    @property
    def images_collected(self) -> bool: ...
    @property
    def images_partially_collected(self) -> bool: ...
    @property
    def images_count(self) -> int: ...
    @property
    def video_created(self) -> bool: ...
    def set_video_created(self) -> None: ...
    def reset_video_created(self) -> None: ...
    def increase_images(self) -> None: ...
    def reset_images_counter(self) -> None: ...
    def set_all_images_collected(self) -> None: ...
    def set_images_partially_collected(self) -> None: ...
    def reset_all_images_collected(self) -> None: ...
    def reset_images_partially_collected(self) -> None: ...
    def get_frame_bytes(self) -> bytes | None: ...
