from logging import Logger
from .weather_station_info import WeatherStationInfo
from abc import ABC, abstractmethod
from playwright.sync_api import Browser, ElementHandle, Page, Playwright
from typing import Any

class Source(ABC):
    logger: Logger
    location_name: str
    url: str
    weather_data_provider: WeatherStationInfo | None
    owner: str | None
    def __init__(
        self,
        location_name: str,
        url: str,
        logger: Logger | None = ...,
        weather_data_on_images: bool =  False,
        weather_data_provider: WeatherStationInfo | None = ...,
        owner: str | None = ...,
        skip_validation: bool = False,
    ) -> None: ...
    @property
    def weather_data_on_images(self) -> bool: ...
    @property
    def is_valid_url(self) -> bool: ...
    @property
    def images_collected(self) -> bool: ...
    @property
    def images_partially_collected(self) -> bool: ...
    @property
    def images_count(self) -> int: ...
    @property
    def daily_videos_count(self) -> int: ...
    @property
    def daily_video_created(self) -> bool: ...
    @property
    def monthly_video_created(self) -> bool: ...
    def set_daily_video_created(self) -> None: ...
    def reset_daily_video_created(self) -> None: ...
    def set_monthly_video_created(self) -> None: ...
    def reset_monthly_video_created(self) -> None: ...
    def increase_images(self) -> None: ...
    def reset_images_counter(self) -> None: ...
    def set_videos_count(self, count: int) -> None: ...
    def reset_daily_videos_counter(self) -> None: ...
    def set_all_images_collected(self) -> None: ...
    def set_images_partially_collected(self) -> None: ...
    def reset_all_images_collected(self) -> None: ...
    def reset_images_partially_collected(self) -> None: ...
    @abstractmethod
    def get_frame_bytes(self) -> bytes | None: ...
    @abstractmethod
    def validate_url(cls, url: str) -> bool: ...

class ImageSource(Source):
    def validate_url(self, url: str) -> bool: ...
    def get_frame_bytes(self) -> bytes | None: ...

class StreamSource(Source):
    OPEN_TIMEOUT_MS: int
    READ_TIMEOUT_MS: int
    CAPTURE_WALL_TIMEOUT_S: float
    @staticmethod
    def get_url_with_yt_dlp(url: str) -> str: ...
    @staticmethod
    def _open_capture(url: str) -> object: ...
    def _read_frame(self, url: str) -> tuple[bool, object | None]: ...
    def validate_url(self, url: str) -> bool: ...
    def get_frame_bytes(self) -> bytes | None: ...

class BrowserSource(Source):
    PAGE_LOAD_TIMEOUT_MS: int
    ELEMENT_TIMEOUT_MS: int
    BLANK_BRIGHTNESS_THRESHOLD: float
    DISMISS_TIMEOUT_MS: int
    _pw: Playwright | None
    _browser: Browser | None
    _page: Page | None
    def __init__(
        self,
        location_name: str,
        url: str,
        selector: str | None = ...,
        persistent_session: bool = False,
        dismiss_selectors: list[str] | None = ...,
        logger: Logger | None = ...,
        weather_data_on_images: bool = ...,
        weather_data_provider: WeatherStationInfo | None = ...,
        owner: str | None = ...,
        skip_validation: bool = False,
    ) -> None: ...
    @property
    def selector(self) -> str | None: ...
    @selector.setter
    def selector(self, value: str) -> None: ...
    @property
    def persistent_session(self) -> bool: ...
    @property
    def dismiss_selectors(self) -> list[str]: ...
    def _dismiss_popups(self, page: Page) -> None: ...
    def _ensure_page(self) -> Page: ...
    def close(self) -> None: ...
    def _find_element(self, page: Page) -> ElementHandle | None: ...
    def _is_blank_frame(self, jpeg_bytes: bytes) -> bool: ...
    def _screenshot_page(self, page: Page) -> bytes | None: ...
    def _capture_screenshot(self, url: str) -> bytes | None: ...
    def validate_url(self, url: str) -> bool: ...
    def get_frame_bytes(self) -> bytes | None: ...
    def __getstate__(self) -> dict[str, Any]: ...
    def __setstate__(self, state: dict[str, Any]) -> None: ...